name: Build App_WifiTransfer ARMHF (R36S)

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm/v7

      - name: Build in ARM32v7 Docker
        uses: addnab/docker-run-action@v3
        with:
          image: arm32v7/ubuntu:20.04
          options: --platform linux/arm/v7 -v ${{ github.workspace }}:/workspace -w /workspace
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y build-essential libsdl2-dev
            make DEVICE=R36S CXX=g++ CC=g++ SDL2_CONFIG=sdl2-config

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: App_WifiTransfer_Package
          path: |
            App_WifiTransfer
            res/
